# Generated by Django 4.2.27 on 2026-02-01 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image_url_product_net_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tax_price',
            new_name='tax',
        ),
    ]
