# Generated by Django 4.2.27 on 2026-02-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_tax_price_product_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('out_of_stock', 'Out of Stock'), ('low_stock', 'Low Stock'), ('in_stock', 'In Stock')], default='unknown', max_length=20),
        ),
    ]
