# Generated by Django 4.2.27 on 2026-02-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_stock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('herbal', 'Herbal'), ('kit', 'Kit')], default='unknown', max_length=20),
        ),
    ]
